version: '3'
services:
 padavan_exporter:
  image: ghcr.io/bpazy/padavan_exporter:arm64-master
  restart: always
  ports:
      - "9101:9100"
  command: ["--padavan.ssh.host=192.168.1.1:22", "--padavan.ssh.username=admin", "--padavan.ssh.password=PASSWORD"]
